CREATE DATABASE IF NOT EXISTS usuarios_db;
CREATE DATABASE IF NOT EXISTS academico_db;
CREATE DATABASE IF NOT EXISTS matricula_db;
CREATE DATABASE IF NOT EXISTS evaluacion_db;
CREATE DATABASE IF NOT EXISTS asistencia_db;