spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academico_db;
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true