server:
  port: 8084

spring:
  application:
    name: ms-evaluaciones

  datasource:
    url: jdbc:mysql://localhost:3306/evaluacion_db
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true